# Generated by Django 5.1.1 on 2024-09-24 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('owner', models.CharField(max_length=50)),
                ('deadline', models.DateField()),
                ('completed', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('color', models.CharField(default='black', max_length=20)),
                ('background_color', models.CharField(default='#f8f9fa', max_length=20)),
            ],
        ),
    ]
