# Generated by Django 5.1.1 on 2024-10-05 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todos',
            options={'ordering': ['-created_at'], 'verbose_name': 'Todo', 'verbose_name_plural': 'Todos'},
        ),
    ]
